name: TestingScript
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with: 
          java-version: 1.8
      - name: Test Backend Classes
        run: |
          javac TestBackend.java
          java TestBackend
      - name: Cleanup
        run: rm TestBackend.class      
    
