name: TestingScript
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with: 
          java-version: 1.8
      - name: Compile Java
        run: |
          javac Test.java
          java Test
          rm Test.class
